######################################################################
# Automatically generated by qmake (2.01a) Tue Jun 25 23:24:33 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += globj.h mainwindow.h
SOURCES += globj.cpp main.cpp mainwindow.cpp
QT += opengl
